language: go
sudo: false
go:
  - 1.8
git:
  depth: 3

install:
  - make install

go_import_path: github.com/nightlegend/apigateway

script:
  - make vet
  - make fmt-check
  - make embedmd
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)